channels:
- conda-forge
dependencies:
- python=3.10.4
- pip<=22.1.2
- pip:
  - mlflow==2.15.0
  - cloudpickle==3.0.0
  - feature-engine==1.8.0
  - numpy==1.22.4
  - pandas==2.2.2
  - psutil==5.9.4
  - scikit-learn==1.5.1
  - scipy==1.13.1
name: mlflow-env
