channels:
- conda-forge
dependencies:
- python=3.9.12
- pip<=21.2.4
- pip:
  - mlflow==2.15.0
  - cloudpickle==2.0.0
  - feature-engine==1.8.0
  - numpy==1.22.4
  - pandas==2.2.2
  - psutil==5.8.0
  - scikit-learn==1.5.1
  - scipy==1.7.3
name: mlflow-env
